/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import Hospital.Hospital;
import Patient.Patient;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAFOURA KAMARA
 */
public class Doctor extends javax.swing.JFrame {
    private Object docpatient;

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        play = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        updat = new javax.swing.JButton();
        back = new javax.swing.JButton();
        details = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ptable1 = new javax.swing.JTable();
        see = new javax.swing.JTextField();
        patientN1 = new javax.swing.JTextField();
        patientN2 = new javax.swing.JTextField();
        patientN3 = new javax.swing.JTextField();
        patientN4 = new javax.swing.JTextField();
        patientN5 = new javax.swing.JTextField();
        patientN6 = new javax.swing.JTextField();
        patientN7 = new javax.swing.JTextField();
        patientN8 = new javax.swing.JTextField();

        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Date  of Birth", "Patient Address", "Phone Number", "Phone Email", "Doctor to see"
            }
        ));
        jScrollPane2.setViewportView(ptable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RokupaHospitalManagementSystem(Doctor' form)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 930, 80));

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        play.setColumns(20);
        play.setRows(5);
        jScrollPane1.setViewportView(play);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 460, 340));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        updat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        updat.setText("Update");
        updat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        details.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        details.setText("Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton5.setText("Patient");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        delet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delet.setText("delete");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(updat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(details)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updat)
                        .addComponent(back)
                        .addComponent(details)
                        .addComponent(jButton5)
                        .addComponent(delet))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 450, 70));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Doctor Name:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Date of Birth:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Doctor  Address:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Phone Number:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Doctor  Email Addr:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Patient to see:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 180, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Doctor specialization:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 200, 30));

        ptable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ptable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name  ", "Date  of Birth", "Doctor Address ", "Phone Number", "Doctor Emai addrl ", "Doctor specialization", "Patient to see "
            }
        ));
        jScrollPane3.setViewportView(ptable1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 910, 190));

        see.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(see, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 170, 30));

        patientN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, 30));

        patientN2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, 30));

        patientN3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, 30));

        patientN4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 170, 30));

        patientN5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 170, 30));

        patientN6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, 30));

        patientN7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 170, 30));

        patientN8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(patientN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ptable1.getModel();
        model.addRow(new Object[]{patientN1.toString(),
        patientN4.getText(),patientN5.getText(),patientN6.getText(),patientN7.getText(),patientN8.getText(),see.getText(),});

    }//GEN-LAST:event_updatActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Hospital iHospital = new Hospital();
        iHospital.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        // TODO add your handling code here:
        String Qty1 = (patientN1.getText());
        String Qty2 = (patientN4.getText());
        String Qty3 = (patientN5.getText());
        String Qty4 = (patientN6.getText());
        String Qty5 = (patientN7.getText());
        String Qty6 = (patientN8.getText());
        String Qty7 = (see.getText());

       play.setText("");
        play.append("\t\n\tHospital Management(Patient Form)\n"
            +"\nPatient Name:\t\t" + Qty1
            +"\nDate Of Birth:\t\t" + Qty2
            +"\nPatient Address:\t" + Qty3
            +"\nPhone Number:\t\t" + Qty4
            +"\nPhone Email:\t\t" + Qty5
            +"\nDoctor to see:\t\t" + Qty6
            +"\n\n\tPatient Instruction we have introduce a \n\tfree text confirmation\n\t"
            + "TEXT REMINDER FOR APPOINTMENT ");

    }//GEN-LAST:event_detailsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            play.print();
        }catch(PrinterException ex){
            Logger.getLogger(System.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 Patient iPatient = new Patient();
        iPatient.setVisible(true);   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
        DefaultTableModel model = (DefaultTableModel) ptable1.getModel();
     if (ptable1.getSelectedRow() ==-1){
      if (ptable1.getRowCount()==0){
          
          JOptionPane.showMessageDialog(null,"No data to delet","Hospital Management System",
                  JOptionPane.OK_OPTION);
      
 }else{
      JOptionPane.showMessageDialog(null,"Select a row to delet","Hospital Management System",
                  JOptionPane.OK_OPTION);
     }
     }else{
     
     model.removeRow(ptable1.getSelectedRow());
     }
    }//GEN-LAST:event_deletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton delet;
    private javax.swing.JButton details;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField patientN1;
    private javax.swing.JTextField patientN2;
    private javax.swing.JTextField patientN3;
    private javax.swing.JTextField patientN4;
    private javax.swing.JTextField patientN5;
    private javax.swing.JTextField patientN6;
    private javax.swing.JTextField patientN7;
    private javax.swing.JTextField patientN8;
    private javax.swing.JTextArea play;
    private javax.swing.JTable ptable;
    private javax.swing.JTable ptable1;
    private javax.swing.JTextField see;
    private javax.swing.JButton updat;
    // End of variables declaration//GEN-END:variables
}
