/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;
import Doctor.Doctor;
import Login.Login;
import Patient.Patient;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SAFOURA KAMARA
 */
public class Hospital extends javax.swing.JFrame {

    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel20 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        software = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        select = new javax.swing.JComboBox();
        reno = new javax.swing.JTextField();
        dos = new javax.swing.JTextField();
        notablets = new javax.swing.JTextField();
        lot = new javax.swing.JTextField();
        issue = new javax.swing.JTextField();
        exp = new javax.swing.JTextField();
        daily = new javax.swing.JTextField();
        possible = new javax.swing.JTextField();
        information = new javax.swing.JTextField();
        advice = new javax.swing.JTextField();
        driving = new javax.swing.JTextField();
        use = new javax.swing.JTextField();
        pid = new javax.swing.JTextField();
        nhc = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        birth = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        effect = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        appointment = new javax.swing.JButton();
        patient = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        login = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        doctor = new javax.swing.JButton();
        priscribtion = new javax.swing.JButton();
        safu1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1019, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(102, 102, 102));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jLabel2.setText("Rokupa Hospital Management System");
        jPanel20.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, 880, 40));

        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        software.setColumns(20);
        software.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        software.setRows(5);
        software.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(software);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 410, 410));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Pricription");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 320, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 590, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Name of Tablet:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Reference No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Dosage(mg):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Number of Tablets:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("LOT:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Issued Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("EXP Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Daily Dosage");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Possible effect:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 120, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Futher information:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Stroage Advice:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 170, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Driving and medical No:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 160, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("How to use medication");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Patient ID:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 130, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("NHS Number:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 130, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Patient Name:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 130, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Date of Birth:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Patient Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 130, 30));

        select.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make a Selection", "Ibuprofen", "Co-Codamos", "Paracetamol", "Amiodip", " " }));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, 30));

        reno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(reno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, 30));

        dos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, 30));

        notablets.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(notablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 150, 30));

        lot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, 30));

        issue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 150, 30));

        exp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 150, 30));

        daily.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(daily, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 150, 30));

        possible.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(possible, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 150, 30));

        information.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 150, 30));

        advice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(advice, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 150, 30));

        driving.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(driving, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, 30));

        use.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(use, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 150, 30));

        pid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 150, 30));

        nhc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(nhc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 150, 30));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 150, 30));

        birth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 150, 30));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 150, 30));

        effect.setBackground(new java.awt.Color(0, 0, 0));
        effect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        effect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        effect.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        effect.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        effect.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 510, 1300, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 510, 1300, 60));

        effect.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1300, 60));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 510, 1300, 60));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 620, 400));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 510, 1300, 60));

        jPanel11.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1300, 60));

        effect.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1300, 60));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        effect.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        effect.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        appointment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        appointment.setText("Gp Appointment");
        effect.add(appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 140, -1));

        patient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patient.setText("Patient");
        patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientActionPerformed(evt);
            }
        });
        effect.add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        effect.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        effect.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        effect.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, 30));

        doctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doctor.setText("Doctor");
        doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorActionPerformed(evt);
            }
        });
        effect.add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        priscribtion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        priscribtion.setText("prescribtion");
        priscribtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priscribtionActionPerformed(evt);
            }
        });
        effect.add(priscribtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 120, -1));

        safu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        safu1.setText("Print");
        safu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                safu1ActionPerformed(evt);
            }
        });
        effect.add(safu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, 30));

        getContentPane().add(effect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1000, 60));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablet", "Reference NO", "Dosage (mg)", "No of Tabet", "LOT", "Issued Date", "EXp Date", "Daily", "Possible effect", "Futher information", "Stroage Advice", "Driving and medical No", "How to use medication", "Patient ID", "NCH Number", "Patient Name", "Patient Date of Birth", "Patient Address"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1000, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
                if(select.getSelectedItem().equals("Ibuprofen"))
        {
        reno.setText("ibu547832");
        dos.setText("2");
        
        notablets.setText("30");
        lot.setText("235678");
        issue.setText("07/05/2019");
        exp.setText("07/05/2021");
        daily.setText("4");
        possible.setText("weakness");
        information.setText("place Dispensary");
        advice.setText("less than 30%");
        driving.setText("No");
        use.setText("Use water No Alcohol");
       pid .setText("ibu222");
        nhc.setText("646566");
       
       
        
        
        }
     else if (select.getSelectedItem().equals("Co-Codamos"))
        {
         reno.setText("coco4567");
        dos.setText("50");
        
        notablets.setText("30");
        lot.setText("B35678");
        issue.setText("03/05/2019");
        exp.setText("03/05/2021");
        daily.setText("2");
        possible.setText("Sakineffection");
        information.setText("place Dispensary");
        advice.setText("less than 20%");
        driving.setText("No");
        use.setText("Use water No Alcohol");
       pid .setText("coco333");
         nhc.setText("606461");
       
      
        
      }
         else if (select.getSelectedItem().equals("Paracetamol"))
         {
         reno.setText("para4567");
        dos.setText("5");
        
        notablets.setText("25");
        lot.setText("P35678");
        issue.setText("05/03/2019");
        exp.setText("05/03/2021");
        daily.setText("1");
        possible.setText("Heart Faliu");
        information.setText(" Effect the Navos System");
        advice.setText("less than 20%");
        driving.setText("No");
        use.setText("Use water No Alcohol");
       pid .setText("para444");
        nhc.setText("3456461");
        
        
        
        }
        else if (select.getSelectedItem().equals("Amiodip"))
         {
         reno.setText("Am4567");
        dos.setText("5");
        
        notablets.setText("25");
        lot.setText("A35678");
        issue.setText("05/03/2019");
        exp.setText("05/03/2021");
        daily.setText("1");
        possible.setText("Liver Disease");
        information.setText("The ability to drive may be affected");
        advice.setText("less than 20%");
        driving.setText("No");
        use.setText("Use water No Alcohol");
       pid .setText("amo444");
        
        nhc.setText("3456461");
        
        
        
        }
          else if (select.getSelectedItem().equals("Make a Selection"))
         {
         reno.setText("");
        dos.setText("");
        notablets.setText("");
        lot.setText("");
        issue.setText("");
        exp.setText("");
        daily.setText("");
        possible.setText("");
        information.setText("");
        advice.setText("");
        driving.setText("");
        use.setText("");
       pid .setText("");
        
        nhc.setText("");
        
        
        
        }

        

    }//GEN-LAST:event_selectActionPerformed

    private void priscribtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priscribtionActionPerformed
String Qty1 = (reno.getText());
         String Qty2 = (dos.getText());
          String Qty3 = (notablets.getText());
           String Qty4 = (lot.getText());
            String Qty5 = (daily.getText());
             String Qty6 = (possible.getText());
              String Qty7 = (information.getText());
               String Qty8 = (use.getText());
                String Qty9 = (pid.getText());
                 String Qty10 = (name.getText());
                  String Qty11 = (birth.getText());
                   String Qty12= (address.getText());
                    String Qty13 = "";
                    
                      if(select.getSelectedItem().equals("Ibuprofen"))
        {
        
        Qty13 = "Ibuprofen";
        }
                      
                   else         if(select.getSelectedItem().equals("Co-Codamos"))
        {
        
        Qty13 = "Co-Codamos";
        }           
                    
                       else    if(select.getSelectedItem().equals("Paracetamol"))
        {
        
        Qty13 = "Paracetamol";
        }          
                    
                    else       if(select.getSelectedItem().equals("Amiodip"))
        {
        
        Qty13 = "Amiodip";
        }          
                     software.setText("");
                     software.append("\t\n\tHospital Management\n"
                     +"\nPatient Name:\t\t" + Qty10
                     +"\nDate Of Birth:\t\t" + Qty11
                     +"\nPatient Address:\t" + Qty12
                     +"\nPrescription:\t\t" + Qty13
                     +"\nReference Number:\t" + Qty1
                     +"\nDose:\t\t\t" + Qty2
                     +"\nNumber of Tabelt:\t" + Qty3
                     +"\nLot:\t\t\t" + Qty4
                     +"\nDaily Dose:\t\t" + Qty5
                     +"\nPossible Effect:\t" + Qty6
                     +"\nfurther Information:\t" + Qty7
                     +"\nHow to use Medication:\t" + Qty8
                     +"\nPatient ID:\t\t" + Qty9
                     +"\n\n\tPatient Instruction we have introduce a \n\tfree text confirmation\n\t"
                                 + "TEXT REMINDER FOR APPOINTMENT ");

    }//GEN-LAST:event_priscribtionActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
    if(JOptionPane.showConfirmDialog(frame,"Confirm If You Wants To Exit", "HospitalManagementSystem",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        
    }
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reno.setText("");
        dos.setText("");
        notablets.setText("");
        lot.setText("");
        issue.setText("");
        exp.setText("");
        daily.setText("");
        possible.setText("");
        information.setText("");
        advice.setText("");
        driving.setText("");
        use.setText("");
       pid .setText("");
        
        nhc.setText("");
        name.setText("");
        birth.setText("");
        software.setText("");
        address.setText("");
        select.getModel().setSelectedItem("Make a Selection");
        

    }//GEN-LAST:event_resetActionPerformed

    private void safu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_safu1ActionPerformed
        // TODO add your handling code here:
                try{
            software.print();
        }catch(PrinterException ex){
            Logger.getLogger(System.class.getName()).log(Level.SEVERE,null,ex);
        }

    }//GEN-LAST:event_safu1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      DefaultTableModel model = (DefaultTableModel) table.getModel();
      model.addRow(new Object[]{select.getSelectedItem().toString(),
      reno.getText(),dos.getText(),notablets.getText(),lot.getText(),issue.getText(),exp.getText(),daily.getText(),possible.getText(),information.getText(),advice.getText(),driving.getText(),use.getText(),pid.getText(),nhc.getText(),name.getText(),birth.getText(),address.getText(),});
      
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     DefaultTableModel model = (DefaultTableModel) table.getModel();
     if (table.getSelectedRow() ==-1){
      if (table.getRowCount()==0){
          
          JOptionPane.showMessageDialog(null,"No data to delet","Hospital Management System",
                  JOptionPane.OK_OPTION);
      
 }else{
      JOptionPane.showMessageDialog(null,"Select a row to delet","Hospital Management System",
                  JOptionPane.OK_OPTION);
     }
     }else{
     
     model.removeRow(table.getSelectedRow());
     }
    }//GEN-LAST:event_deleteActionPerformed

    private void patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientActionPerformed
      Patient iPatient = new Patient();
        iPatient.setVisible(true);
    }//GEN-LAST:event_patientActionPerformed

    private void doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorActionPerformed
 Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);      
    }//GEN-LAST:event_doctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField advice;
    private javax.swing.JButton appointment;
    private javax.swing.JTextField birth;
    private javax.swing.JTextField daily;
    private javax.swing.JButton delete;
    private javax.swing.JButton doctor;
    private javax.swing.JTextField dos;
    private javax.swing.JTextField driving;
    private javax.swing.JPanel effect;
    private javax.swing.JButton exit;
    private javax.swing.JTextField exp;
    private javax.swing.JTextField information;
    private javax.swing.JTextField issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton login;
    private javax.swing.JTextField lot;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nhc;
    private javax.swing.JTextField notablets;
    private javax.swing.JButton patient;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField possible;
    private javax.swing.JButton priscribtion;
    private javax.swing.JTextField reno;
    private javax.swing.JButton reset;
    private javax.swing.JButton safu1;
    private javax.swing.JComboBox select;
    private javax.swing.JTextArea software;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    private javax.swing.JTextField use;
    // End of variables declaration//GEN-END:variables
}
